language: node_js
node_js:
  - "7"
install:
  - npm install
cache:
  directories:
    - node_modules

jobs:
  include:
    - # release check
      if: branch != production AND type IN (pull_request)
      script:
      - npm run test
      - npm run jshint
      - npm run release-check
  include:
    - # release
      if: branch = master AND type IN (push)
      script:
      - echo "OK"
