language: node_js
node_js:
  - "7"
install:
  - npm install
cache:
  directories:
    - node_modules

jobs:
  include:
    - # test 1
      if: NOT branch = production AND type IN (pull_request)
      script:
      - echo "IS NOT production branch"
  include:
    - # test 2
      if: branch = production AND type IN (push)
      script:
      - echo "IS production branch"
