language: node_js
node_js:
  - "7"
install:
  - npm install
cache:
  directories:
    - node_modules
jobs:
  include:
    - # release check
      if: NOT (branch = production)
      script:
        - npm run test
        - npm run jshint
        - npm run release-check
    - # release
      if: (branch = production)
      script:
        - npm run release
